### ISSUE TITLE
报告Bug：ADD Hearder 是无效的 

### ISSUE THREAD

**Issue by limory** [0140454/hackbar#1]
当我打开一个网站，点击load url，点击 ADD Hearder ，选择referer或者User-Agent，在Value填好值以后，点击execute url，虽然网站刷新了，但是刚才设置的referer或者User-Agent，都没有生效！
我是通过print_r($_SERVER)，或者Apache access_log，查看输出信息，我在hackbar设置的值并没有生效！！！请问作者怎么回事呢？
-------------版本信息---------------------
HackBar 0.2.14
Google Chrome 70.0.3538.110（正式版本） （64 位）
Win7 64Bit

**Comment by 0140454** [comment]
Please upgrade to v0.2.15 and try it again.

**Comment by limory** [comment]
It's OK! it's working now! Thks!
