### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Ugroon** [0140454/hackbar#10]

**Comment by Ugroon** [comment]
I pressed Alt +a don't work. So, i try press ctrl + shift + I but still don't work

**Comment by 0140454** [comment]
You need to open Developer Tools first. Then, you can use shortcuts to load/execute request.

If there is no response when you use shortcuts, please go to Keyboard Shortcuts tab in chrome://extensions to review your settings. Maybe Ctrl + A has been registered by another extension.

**Comment by 0140454** [comment]
Close due to inactive.
