### ISSUE TITLE
A bug about URL

### ISSUE THREAD

**Issue by h3zh1** [0140454/hackbar#11]
When I used Hackbar on my macbook, I found a bug: when I used command+a to select all in the URL bar of chrome, it would be invalid, and I had to repeat it twice.

**Comment by 0140454** [comment]
Just to let you know, I may need more time to triage it since I use Linux on PC.

**Comment by 0140454** [comment]
Sorry for late. I have reproduced this issue.

However, I think it is Chrome or Mac OS issue since other extension with same shortcut setting can reproduce the issue too.

Here is my test video.
https://user-images.githubusercontent.com/1191368/170872571-ad7e19b8-28a5-4e1c-b7e9-06753ade7819.mp4

**Comment by 0140454** [comment]
Therefore, I think I will not do anything here.

**Comment by h3zh1** [comment]
Cool!  Your idea is right，Thanks a lot!

**Comment by splitline** [comment]
@0140454 
I encountered just the same bug here.
Do you consider to replace MacCtrl with just alt or something? This bug is pretty annoying which makes me need to disable this extension temporarily lmao

**Comment by 0140454** [comment]
Make macOS use default shortcut settings in the latest commit. It may takes some days to publish on Chrome store.

**Comment by 0140454** [comment]
BTW, if the settings doesn't change after extension updated, you need to manually setup it.
