### ISSUE TITLE
firefox不能用，太遗憾了

### ISSUE THREAD

**Issue by 866666** [0140454/hackbar#17]
firefox不能用，太遗憾了

**Comment by 0140454** [comment]
I will try to make it work in Chrome and Firefox in the future.
It may land in v1.0.0, which use manifest version 3.

**Comment by 189169** [comment]
Great, it will become the best plug-in on Firefox.

**Comment by birdofprey** [comment]
> firefox不能用，太遗憾了

> firefox不能用，太遗憾了+1

**Comment by 866666** [comment]
您发给我的邮件已经被收到

**Comment by 0140454** [comment]
FYI

To make it work in Firefox and Chrome with minimal or no changes, I have refactored it using `webextension-polyfill`.

But, there are some issues needed to be resolved. The release will be postponed until they are solved.

Known issues:
- Chrome
  - [webRequest listeners not called after service worker stops](https://bugs.chromium.org/p/chromium/issues/detail?id=1024211)
- Firefox
  - [There is no in-memory storage API (storage.session)](https://bugzilla.mozilla.org/show_bug.cgi?id=1687778)
  - [There is no DeclarativeNetRequest (DNR) API](https://bugzilla.mozilla.org/show_bug.cgi?id=1687755)

Of course, if you want to try the early release, you can download a compiled Firefox version in Release page, enable Firefox's MV3 support and then install it manually.

**Comment by 0140454** [comment]
**Status Update**

Firefox version will be released after required APIs are implemented by Mozilla, and its version may be v1.1.0.

**Comment by 866666** [comment]
您发给我的邮件已经被收到

**Comment by 866666** [comment]
您发给我的邮件已经被收到
