### ISSUE TITLE
What is the Output position?

### ISSUE THREAD

**Issue by houzhishi** [0140454/hackbar#2]
In SQLI.I tried setting but it didn't change.

**Comment by 0140454** [comment]
**Output position**

It indicates which column you want to use to print the information.

If there are three columns in the query and only the second column appears on the page, your setting should be as the following.
* The number of columns: 3
* Output position: 2

**Generated payload example**
```
union select 1,group_concat(schema_name),3 from information_schema.schemata
```

**Comment by houzhishi** [comment]
Maybe I didn’t make it clear.
I am referring to the Union select statement under SQLI.
This Output position does not work.

**Comment by 0140454** [comment]
Oh, in fact, **Output position** doesn't affect the output of ```Union select statement``` because I just use it to help me locate visible columns.

I will make it clear in next release.

**Comment by houzhishi** [comment]
Thank you for your answer.
