### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by datouo** [0140454/hackbar#25]
1. 新版的Hackbar无法使用command+z、ctrl+z撤销操作，有点难受，尤其是在需要使用Hackbar进行编码时
2. load的功能似乎新增了校验工作，这导致在某些特殊的网页无法正常load url，感觉这个校验的工作没啥必要，毕竟使用这个工具的用户一般都具备手动debug URL的能力
3. 在使用新版的Hackbar操作反弹shell时，一般反弹shell的进程都是阻塞的，导致Hackbar发送一次请求之后会一直转圈圈，无法再发第二次请求，这样的体验挺糟糕的
4. 新版似乎把LFI的Payload删除了，不知道为啥把LFI删除了，希望能加回来
5. 希望能添加一个新的url编码方式（能给abcdefg这类字符编码），也就是URL全编码，比如把`abcd`编码成`%61%62%63%64`

**Comment by 0140454** [comment]
1. Investigating.
2. Please provide an example.
3. Fixed (f4649fe8edc602f6034a359e12d7633c72866693).
   Overlay removed.
   I may use snackbar to prompt that the request is executing in the future.
4. Added (28bf7eb1bfdaa5bdaad965d2f76a2c277b592016).
5. Added (cc0cd20ac3bb3ade74f57a44e780afba17f8db2f).
6. Please provide an example.
   As the following, I cannot reproduce it.
   * Basic mode
     ![image](https://user-images.githubusercontent.com/1191368/209151017-7e28acad-e199-4bb2-93ca-727133295b9f.png)
   * Raw mode
     ![image](https://user-images.githubusercontent.com/1191368/209150774-8d341354-f15e-4a4f-9bd2-fc3ecb7b5462.png)

**Comment by 0140454** [comment]
After investigation, the cause to first issue is that Chrome called `e.preventDefault()` [here](https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/models/extensions/ExtensionAPI.ts;l=1300;bpv=1;bpt=0).

And we can also observe the same behaviour in other extension, such as **Vue.js devtools**.
The following is testing video. I try to undo typed six "a" characters via Ctrl-Z, but it doesn't perform expected action in both of **HackBar** and **Vue.js devtools**.

<video src="https://user-images.githubusercontent.com/1191368/209376919-99407fa2-554a-4eb0-b7a4-b7a9cebd41e9.webm"></video>

If you would like to verify what I found, you can follow the instructions:
1. Apply the following patch.
   ```diff
   --- a/src/main.ts
   +++ b/src/main.ts
   @@ -11,4 +11,10 @@ import './generators/encode'
    import './generators/hash'
    import './generators/payload'
    
   +const oldFunc = Event.prototype.preventDefault
   +Event.prototype.preventDefault = function () {
   +  debugger
   +  oldFunc.call(this)
   +}
   +
    createApp(App).use(vuetify).mount('#app')
   ```
2. Build extension and install it
3. Open HackBar and devtools for it
4. Enter some characters and try to use Ctrl-Z to undo it
5. You will find that the execution is paused
   and according to Call Stack, the caller of `e.preventDefault` is a function provided by Chrome

**Comment by 0140454** [comment]
Just for update, a workaround has been implemented.
