### ISSUE TITLE
传入GET参数的同时传入POST参数，执行无反应

### ISSUE THREAD

**Issue by 866666** [0140454/hackbar#35]
一个CTF例题：
http://catf1ag.cn/trouble/179

http://subject.catf1ag.cn:41600/?flag=cat 
同时 POST flag=f1ag

无响应

试用curl 命令可以正常执行成功

edge 浏览器

**Comment by 0140454** [comment]
Could you tell me which mode you used?

**Comment by 866666** [comment]
> 你能告诉我你使用了哪种模式吗？

我尝试了两种MODE,包括basic和raw，切换到raw模式是这样的请求：
![1](https://github.com/0140454/hackbar/assets/48896240/44b5b458-681a-4985-85c1-6efab823fe53)
![2](https://github.com/0140454/hackbar/assets/48896240/bf046d2b-45eb-4a0b-89e1-f0b50904af46)

点击execute后 并未产生POST请求

**Comment by 866666** [comment]
这是我用另一个插件执行POST成功后的请求头：
POST /?flag=cat HTTP/1.1
Host: subject.catf1ag.cn:45130
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 9
Origin: http://subject.catf1ag.cn:45130
Connection: keep-alive
Referer: http://subject.catf1ag.cn:45130/?flag=cat
Upgrade-Insecure-Requests: 1

**Comment by 866666** [comment]
我已经找到原因了，很抱歉，是我本机的CLASH代理转发了部分请求
