### ISSUE TITLE
hackbar cannot be used

### ISSUE THREAD

**Issue by Amoxicillin419** [0140454/hackbar#36]
hackbar plugin cannot be used on the Chrome browser,Chrome version is 114.0.5735.198，runing on Macbook on Apple sillicon.hackbar plugin version is 1.1.4 . prompt this extension maybe corrupted

**Comment by 0140454** [comment]
I tested HackBar v1.1.4 in Chrome 114.0.5735.198 on Linux. It works as expected.

Could you provide some screenshot?

**Comment by 0140454** [comment]
Close due to inactive.
