### ISSUE TITLE
X-Forwarded-For don't work

### ISSUE THREAD

**Issue by laiquziru** [0140454/hackbar#37]
![微信图片_20230729200907](https://github.com/0140454/hackbar/assets/31889178/150562da-c97b-4fda-acc1-def018507520)

X-Forwarded-For don't work    post必须带变量名

**Comment by 0140454** [comment]
Modified headers only apply on the initiated request. The following request (e.g. redirected request triggered by HTTP 302) will not be affected.

Therefore, you should change your path.

![image](https://github.com/0140454/hackbar/assets/1191368/ca4b28ca-f868-47fc-8395-0953db4cc752)
