### ISSUE TITLE
希望可以添加自定义payload  谢谢

### ISSUE THREAD

**Issue by laiquziru** [0140454/hackbar#38]
希望可以添加自定义payload  谢谢

**Comment by 0140454** [comment]
Do you mean that you want to add custom payload to top menu bar?

If yes, could you tell me which type you want to add?
* Fixed payload
* Payload with arguments, like those in Shell category
This information will let me know how to design it.

**Comment by 0140454** [comment]
Do you mean that you want to add custom payload to top menu bar?

If yes, could you tell me which type you want to add?
* Fixed payload
* Payload with arguments, like those in Shell category

Furthermore, do you want to sync added payload between your browsers?

These information will let me know how to design it.

**Comment by laiquziru** [comment]
Yes, I want to add a payload I wrote myself. I don’t know if the plugin can support it. This will improve the efficiency of my questions. Haha, thank you

**Comment by 0140454** [comment]
Okay, I think I can implement this if I have time.

However, here is the limitation of the first implementation:
* Cannot sync between browsers
* Cannot define placeholder

They may be eliminated in later implementation if needed.

**Comment by laiquziru** [comment]
Okay thinks
