### ISSUE TITLE
Enhance custom payload functionality

### ISSUE THREAD

**Issue by 0140454** [0140454/hackbar#40]
For investigation. May implement it if I have time.

If you want the functionality, just react this comment with the specified emoji.

:+1: for importing / exporting custom payload

:tada: for syncing custom payload between browsers

:heart: for reordering custom payload

:rocket: ~for supporting category (submenu)~

**Comment by laiquziru** [comment]
Hello, you cannot customize the load to load the secondary menu, so it can be classified thanks

**Comment by 0140454** [comment]
Do you mean you want the last one `supporting category (submenu)` ?

**Comment by 0140454** [comment]
> Hello, you cannot customize the load to load the secondary menu, so it can be classified thanks

@laiquziru Do you mean you want the last one `supporting category (submenu)` ?

**Comment by laiquziru** [comment]
yes,like this
![image](https://github.com/0140454/hackbar/assets/31889178/21cf0b48-6264-43d6-a6ad-840ee10eb14a)

**Comment by 0140454** [comment]
Category support implemented in v1.2.2

**Comment by 0140454** [comment]
Close due to stale.
