### ISSUE TITLE
hackbar fail to post data

### ISSUE THREAD

**Issue by AKXF2020** [0140454/hackbar#42]
Somehow hackbar cannot post data I want to the site using the post method. No request packet found in Dev tool "Network". Reinstall this extension will only work for a while until machine restarts.
Browser: Brave 1.61.100 Chromium: 120.0.6099.62

**Comment by 0140454** [comment]
Could you provide the URL to be tested? Thank you

**Comment by AKXF2020** [comment]
I'll correct my statement. "Execute" is not working. Any site would be ok. I did a Google search, load URL and try to modify "-q" to search "111". When I click "Execute", it does nothing.
![Snipaste_2023-12-11_23-35-19](https://github.com/0140454/hackbar/assets/63178001/715569c0-2534-4e1a-ad52-a70aab0108ce)

**Comment by 0140454** [comment]
Tested on Chrome 120.0.6099.71, and `Execute` works as expected.

https://github.com/0140454/hackbar/assets/1191368/6d75a1ca-3520-42a9-a178-99c1b1921b7b

Could you open chrome://extensions/ and check whether there are errors in HackBar?

**Comment by AKXF2020** [comment]
Seems that it's relavant with browser. Eveytime I reload this extension after opening Brave, hackbar would work well. It's strange that no error is found in  brave://extensions/. Anyway I find a way to make it work, thank you!
