### ISSUE TITLE
我安装完hackbar之后，按f12 没显示，在以前是显示的

### ISSUE THREAD

**Issue by manic0** [0140454/hackbar#43]
![微信图片_20240103152807](https://github.com/0140454/hackbar/assets/124340291/4f7a0ded-1d7b-4a9a-87d2-753d35c4a7ef)
这是为什么呢

**Comment by XingXiaoWu** [comment]
same question,how to resolve it

**Comment by WankkoRee** [comment]
如果直接在新标签页打开开发者工具，那么你看不到这个插件，这可能和浏览器安全策略有关。

所以，请在一个已经正常加载的网页中打开开发者工具。

**Comment by XingXiaoWu** [comment]
> 如果直接在新标签页打开开发者工具，那么你看不到这个插件，这可能和浏览器安全策略有关。
> 
> 所以，请在一个已经正常加载的网页中打开开发者工具。

thanks,but i can't find it. I reset my EdgeBrower, then I find it.
