### ISSUE TITLE
V1.2.3 crash

### ISSUE THREAD

**Issue by q1340332267** [0140454/hackbar#44]
Crash when opening the button "use POST method"  Tried reinstalling but it didn't work

but V1.2.2 can be used as usual

**Comment by 0140454** [comment]
I cannot reproduce the crash in Chrome 121.0.6167.85 on Linux.

https://github.com/0140454/hackbar/assets/1191368/fb53718c-625f-4239-a4f4-67c4cee0ed00

Please provide your browser name, browser version and target URL.

**Comment by q1340332267** [comment]
chromeV121.0.6167.86 on win11

**Comment by q1340332267** [comment]
ChromeV121.0.6167.86 on win11

**Comment by q1340332267** [comment]
Chrome V121.0.6167.86 on win11      crash
Chrome V121.0.6167.86 on win10      work

https://github.com/0140454/hackbar/assets/63180919/fa9d90a9-6339-4460-bf8a-34f3afef8d28

**Comment by 0140454** [comment]
Thanks for report.

I will try to get a Windows 11 to test this.

At this moment, you may use Raw mode to send your request.

**Comment by 0140454** [comment]
Unfortunately, I still cannot reproduce it in Chrome 121.0.6167.86 on Windows 11 Pro 23H2 (Build 22631.3007).


https://github.com/0140454/hackbar/assets/1191368/b61148d8-0a5a-43f3-ab56-313b2771e983

**Comment by Adminie** [comment]
Google Chrome 120.0.6099.200   windows11   Crash when opening the button "use POST method" Tried reinstalling but it didn't work

**Comment by HSwift** [comment]
Reproducing the crash in Google Chrome 121.0.6167.85 Linux, HackBar 1.2.3.

And I also found that when the POST method switch is selected, postControlWrapped keeps repeating the calculation, with the result cycling between true and false.

https://github.com/0140454/hackbar/blob/eeb45d557d898b79d4aaedc143a2132693fa078e/src/components/RequestPanelBasic.vue#L194-L200

It seems that the result of enctypeSelectTop and enctypeSelectHeight depend on the value of postControlWrapped, leading to an infinite loop of rendering?

https://github.com/0140454/hackbar/blob/eeb45d557d898b79d4aaedc143a2132693fa078e/src/components/RequestPanelBasic.vue#L27-L31

**Comment by 0140454** [comment]
@HSwift Nice catch!

If you remove code related to `postControlWrapped`, does it work as expected?

If yes, do you want to create a PR to remove them and add yourself into Contributor list in README? I will accept the PR and release new version as soon as possible.

**Comment by 0140454** [comment]
Version 1.2.4 is uploaded to Chrome Web Store and Firefox Add-ons. It is waiting for review now.
