### ISSUE TITLE
show    form.submit is not a function when using POST application/x-www-form-urlencoded from loaded 

### ISSUE THREAD

**Issue by ghostlitao** [0140454/hackbar#48]
![image](https://github.com/0140454/hackbar/assets/2668428/ddd82e7f-7a0e-4c1e-aec6-17792146f69d)

**Comment by 0140454** [comment]
There is a input named as `submit`, so we need to modify code to call the real submit function.

I will fix this in next days. Thanks for reporting bug.

**Comment by ghostlitao** [comment]
> There is a input named as `submit`, so we need to modify code to call the real submit function.
> 
> I will fix this in next days. Thanks for reporting bug.

Understood. 
Thx.

**Comment by Forjoke** [comment]
It is not very stable and often crashes. Can you optimize it?

**Comment by 0140454** [comment]
Please open new issue with details (OS, browser and extension version) and reproducible steps. Do not hijack the issue.
