### ISSUE TITLE
Unexpected \r\n in the end of the body

### ISSUE THREAD

**Issue by 0140454** [0140454/hackbar#5]
Issue is submitted in Chrome Web Store

**Comment by easyjack** [comment]
I see this also

![image](https://user-images.githubusercontent.com/24935499/82155333-b8c2f900-98a6-11ea-9bb0-30c47c8f8d01.png)

**Comment by 0140454** [comment]
Currently, HackBar constructs a `text/plain` form and modifies `content-type` in the background page to simulate `application/x-www-form-urlencoded` (due to #4).

It seems that as long as we use `text/plain` form to simulate it, unexpected \r\n will be added in the end of payload.

I may revert the change in the next few days and use the above-mentioned method only if there is wide-byte in payload.
