### ISSUE TITLE
when POST data  %0a included will extra add %0d

### ISSUE THREAD

**Issue by Fenguopeng** [0140454/hackbar#51]
version:1.2.5
OS: windows 11
Browser: Chrome
![image](https://github.com/0140454/hackbar/assets/13653488/67e1738a-d413-40bc-9185-3ab249bd4a08)
![image](https://github.com/0140454/hackbar/assets/13653488/f02ac878-85b3-410e-bd78-ccf931d6c27e)

**Comment by Fenguopeng** [comment]
when use  `application/x-www-form-urlencoded(raw) `mode, the last will add `0D 0A`，I think this is not necessary。
![image](https://github.com/0140454/hackbar/assets/13653488/8aff46a0-1298-4429-88de-223af7f99d76)

**Comment by 0140454** [comment]
This is expected behavior. See also https://github.com/0140454/hackbar/issues/7#issuecomment-743711606

To avoid trailing CRLF, you need to use normal version `application/x-www-form-urlencoded` or use Raw mode.

**Comment by Fenguopeng** [comment]
Thank you。I found a solution to the problem，the menu `MODE-Raw` can send raw data。
