### ISSUE TITLE
Can I post Raw data ？

### ISSUE THREAD

**Issue by kingfingerpro** [0140454/hackbar#7]
I wanna use hackbar to post raw data (without encoding) , but I can't find any option about this .
![image](https://user-images.githubusercontent.com/58259585/101976775-86824a00-3c83-11eb-8217-22a5770a30db.png)

**Comment by 0140454** [comment]
Currently, HackBar **cannot** POST raw data. Related issue is #4.

Maybe I can add another enctype named as `application/x-www-form-urlencoded (raw data)`; and it is implemented by `text/plain` + change header to `application/x-www-form-urlencoded`.

However, it leads to another issue #5.

Does this meet your needs?

**Comment by kingfingerpro** [comment]
Thank U . I think it worked .
😘

**Comment by 0140454** [comment]
You're welcome.

I will close this issue and find time for adding new enctype as mentioned above.
